services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: tokenizaciondb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: ["5432:5432"]

  mailhog:
    image: mailhog/mailhog
    ports: ["1025:1025", "8025:8025"]


  app:
    build: src/test/java
    depends_on: [db, mailhog]
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: dpg-d2m6lcp5pdvs73bef710-a.oregon-postgres.render.com
      DB_PORT: 5432
      DB_NAME: postgres_token
      DB_USER: postgres_token_user
      DB_PASSWORD: NNOfTfIfBsOYJiHhFWfKB9HqjT48vWiM
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_ENABLED: "true"
      MAIL_FROM: sergioge28@gmail.com
      API_KEY: dev-123
      AES_GCM_KEY_BASE64: ymI5Oo2g2bXWS4FFW/okZI1bXTtvxSVQGXQVx9VhK+I=
      PAYMENT_REJECTION_PROB: "0.3"
      PAYMENT_MAX_ATTEMPTS: "3"
    ports: ["8080:8080"]
